package beans;
// Generated Nov 25, 2015 7:22:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * Doctores generated by hbm2java
 */
public class Doctores {

	private Integer idDoctores;
	private String name;
	private String surname1;
	private String surname2;
	private String email;
	private String pass;

	public Integer getIdDoctores() {
		return this.idDoctores;
	}

	public void setIdDoctores(Integer idDoctores) {
		this.idDoctores = idDoctores;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname1() {
		return this.surname1;
	}

	public void setSurname1(String surname1) {
		this.surname1 = surname1;
	}

	public String getSurname2() {
		return this.surname2;
	}

	public void setSurname2(String surname2) {
		this.surname2 = surname2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

}
