package beans;
// Generated Nov 25, 2015 7:22:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ejercicios generated by hbm2java
 */
public class Ejercicios {

	private Integer idEjercicios;
	private Integer idPac;
	private Date date;
	private Integer length;
	private Integer intensity;

	public Integer getIdEjercicios() {
		return this.idEjercicios;
	}

	public void setIdEjercicios(Integer idEjercicios) {
		this.idEjercicios = idEjercicios;
	}

	public Integer getIdPac() {
		return this.idPac;
	}

	public void setIdPac(Integer idPac) {
		this.idPac = idPac;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public Integer getIntensity() {
		return this.intensity;
	}

	public void setIntensity(Integer intensity) {
		this.intensity = intensity;
	}

}
