package beans;
// Generated Nov 25, 2015 7:22:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes {

	private Integer idPacientes;
	private String name;
	private String surname1;
	private String surname2;
	private Date birthdate;
	private String dni;
	private String email;
	private Integer height;
	private Double weight;
	private Double imc;
	private String diabetesType;
	private String gender;
	private String password;
	private String illnesses;
	private String medication;
	private Integer idDoctor;

	public Integer getIdPacientes() {
		return this.idPacientes;
	}

	public void setIdPacientes(Integer idPacientes) {
		this.idPacientes = idPacientes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname1() {
		return this.surname1;
	}

	public void setSurname1(String surname1) {
		this.surname1 = surname1;
	}

	public String getSurname2() {
		return this.surname2;
	}

	public void setSurname2(String surname2) {
		this.surname2 = surname2;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public String getDiabetesType() {
		return this.diabetesType;
	}

	public void setDiabetesType(String diabetesType) {
		this.diabetesType = diabetesType;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getIllnesses() {
		return this.illnesses;
	}

	public void setIllnesses(String illnesses) {
		this.illnesses = illnesses;
	}

	public String getMedication() {
		return this.medication;
	}

	public void setMedication(String medication) {
		this.medication = medication;
	}

	public Integer getIdDoctor() {
		return this.idDoctor;
	}

	public void setIdDoctor(Integer idDoctor) {
		this.idDoctor = idDoctor;
	}

	public Double getWeight() {
		return weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public Double getImc() {
		return imc;
	}

	public void setImc(Double imc) {
		this.imc = imc;
	}

}
