package beans;
// Generated Nov 25, 2015 7:22:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pesos generated by hbm2java
 */
public class Pesos {

	private Integer idPesos;
	private Integer idPac;
	private Date date;
	private Double value;

	public Integer getIdPesos() {
		return this.idPesos;
	}

	public void setIdPesos(Integer idPesos) {
		this.idPesos = idPesos;
	}

	public Integer getIdPac() {
		return this.idPac;
	}

	public void setIdPac(Integer idPac) {
		this.idPac = idPac;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

}
