package beans;
// Generated Nov 25, 2015 7:22:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pruebas generated by hbm2java
 */
public class Pruebas {

	private Integer idPruebas;
	private Integer idPac;
	private Date date;
	private String value;

	public Integer getIdPruebas() {
		return this.idPruebas;
	}

	public void setIdPruebas(Integer idPruebas) {
		this.idPruebas = idPruebas;
	}

	public Integer getIdPac() {
		return this.idPac;
	}

	public void setIdPac(Integer idPac) {
		this.idPac = idPac;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
