package beans;
// Generated Nov 25, 2015 7:22:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RecoEnv generated by hbm2java
 */
public class RecoEnv {

	private Integer idRecoEnv;
	private int idRec;
	private int idPac;
	private Date fechaRec;

	public Integer getIdRecoEnv() {
		return this.idRecoEnv;
	}

	public void setIdRecoEnv(Integer idRecoEnv) {
		this.idRecoEnv = idRecoEnv;
	}

	public int getIdRec() {
		return this.idRec;
	}

	public void setIdRec(int idRec) {
		this.idRec = idRec;
	}

	public int getIdPac() {
		return this.idPac;
	}

	public void setIdPac(int idPac) {
		this.idPac = idPac;
	}

	public Date getFechaRec() {
		return this.fechaRec;
	}

	public void setFechaRec(Date fechaRec) {
		this.fechaRec = fechaRec;
	}

}
