package beans;
// Generated Nov 25, 2015 7:22:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * Recomendacion generated by hbm2java
 */
public class Recomendacion {

	private Integer idRecomendacion;
	private String titulo;
	private String desc;
	private Integer prio;
	private String causa;

	public Integer getIdRecomendacion() {
		return this.idRecomendacion;
	}

	public void setIdRecomendacion(Integer idRecomendacion) {
		this.idRecomendacion = idRecomendacion;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Integer getPrio() {
		return this.prio;
	}

	public void setPrio(Integer prio) {
		this.prio = prio;
	}

	public String getCausa() {
		return this.causa;
	}

	public void setCausa(String causa) {
		this.causa = causa;
	}

}
